web/projects/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^about/$', views.about, name="about"),
    url(r'^contact/$', views.contact, name="contact"),
    url(r'^projects/$', views.showcase, name="showcase"),
    url(r'^projects/add$', views.add, name="add"),
    url(r'^projects/(?P<slug>[\w-]+)$', views.details, name="view"),
    url(r'^projects/(?P<slug>[\w-]+)/edit$', views.edit, name="edit"),
    url(r'^projects/(?P<slug>[\w-]+)/delete', views.delete, name="delete"),
    url(r'^projects/(?P<slug>[\w-]+)/update', views.update, name="update"),
]

web/reflection/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('projects.urls', namespace='projects')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

web/projects/models.py
from django.db import models
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.core.urlresolvers import reverse


from .utils.update import update


class ProjectManager(models.Manager):
    def featured(self):
        return super(ProjectManager, self).filter(featured=True)

    def not_featured(self):
        return super(ProjectManager, self).filter(featured=False)


class Project (models.Model):
    username = models.CharField(max_length=128)
    repository = models.CharField(max_length=128)
    slug = models.SlugField(max_length=64)
    featured = models.BooleanField(default=False)
    readme = models.TextField(blank=True, help_text="Please update this on github!")
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
    sha = models.CharField(max_length=64, blank=True, editable=False)
    updated_at = models.DateTimeField(auto_now=False, auto_now_add=False)
    download_url = models.URLField(blank=True)
    language = models.CharField(max_length=128)
    description = models.TextField(null=True, blank=True)

    objects = ProjectManager()

    def get_absolute_link(self):
        return reverse("projects:view", kwargs={"slug": self.slug})

    class Meta:
        unique_together = ('username', 'repository', )


def create_slug(instance):
    slug = slugify(instance.repository)
    if Project.objects.filter(slug=slug).exists():
        slug = "%s-%s" % (slug, instance.id)

    return slug


def pre_save_port_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

    update(instance, False)

pre_save.connect(pre_save_port_receiver, sender=Project)

web/projects/forms.py
from django import forms

from .models import Project


class ProjectForm (forms.ModelForm):
    class Meta:
        model = Project
        fields = [
            "username",
            "repository",
            'featured'
        ]

web/projects/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.admin.views.decorators import staff_member_required
from django.conf import settings

import logging

from .models import Project
from .forms import ProjectForm
from .utils.update import update as update_data

log = logging.getLogger(__name__)


def index(request):
    return render(request, 'projects/index.html', {
        "links": settings.LINKS
    })


def about(request):
    return render(request, 'projects/about.html', {})


def contact(request):
    return render(request, 'projects/contact.html', {
        "links": settings.LINKS
    })


def showcase(request):
    log.debug("Index dispatched")
    context = {
        "featured": Project.objects.featured(),
        "not_featured": Project.objects.not_featured().order_by("updated_at")
    }
    return render(request, 'projects/list.html', context)


@staff_member_required
def edit(request, slug):
    log.debug("Edit dispatched")

    instance = get_object_or_404(Project, slug=slug)
    form = ProjectForm(request.POST or None, instance=instance)
    if request.method == "POST":
        if form.is_valid():
            instance = form.save(commit=False)
            instance.save()
            log.debug("Edited project: %s/%s" % (instance.username, instance.repository))
            return HttpResponseRedirect(instance.get_absolute_link())
        else:
            log.warning("Submitted form is not valid")

    context = {
        "form": form
    }
    return render(request, 'projects/add.html', context)


@staff_member_required
def delete(request, slug):
    log.debug("Delete dispatched")

    instance = get_object_or_404(Project, slug=slug)
    instance.delete()

    return redirect("projects:showcase")


@staff_member_required
def update(request, slug):
    log.debug("Update dispatched")

    instance = get_object_or_404(Project, slug=slug)
    update_data(instance)

    return redirect("projects:view", slug=slug)


@staff_member_required
def add(request):
    log.debug("Add dispatched")

    form = ProjectForm(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            instance = form.save(commit=False)
            instance.save()
            log.debug("Added new project: %s/%s" % (instance.username, instance.repository))
            return HttpResponseRedirect(instance.get_absolute_link())
        else:
            log.warning("Submitted form is not valid")

    context = {"form": form}
    return render(request, 'projects/add.html', context)


def details(request, slug):
    log.debug("View dispatched");
    project = get_object_or_404(Project, slug=slug)

    if not project.readme:
        return HttpResponseRedirect("http://github.com/%s/%s/" % (project.username, project.repository))

    log.debug("Project " + project.username + "/" + project.repository + " has been requested")
    return render(request, 'projects/view.html', {'project': project})

web/projects/templates/projects/about.html
{% extends 'reflection/base.html' %}
{% load staticfiles %}

{% block title %}About me // {{ block.super }}{% endblock %}

{% block content %}
    <div class="container about accent-links">
        <h1>Hello! My name is Mircea Mihalea!</h1>

        <p>I'm a passionate programmer and that's why I'm currently studying towards a MEng Computer Science with
            Distributed Systems and Networks at the University of Southampton, with a graduation date of 2019. Having
            just started the second year, I have a clear understading of the foundations of the software engineering
            process, the logical and mathematical foundations of computer science, and how to design and optimise a
            database.
        </p>
        <p>

        <h2>Skills</h2>
        <p> My programming experience is not limited to courseworks and exams, having built several projects
            using a variety of languages such as <a href="{% url 'projects:view' slug='booklibrary'  %}">C#</a> and <a href="{% url 'projects:view' slug='discomatic' %}">Java</a> and a couple of sites using
            <a href="{% url 'projects:view' slug='object' %}">PHP</a> and <a href="{% url 'projects:view' slug='reflection' %}">Python</a>.
        </p>

        <p>
            However, I also love building and administering systems, and that's why I've built and managed my own server
            for the last 5 years. In need of stable distribution, I've opted for Ubuntu Server, but on my personal
            machines I've gone through a variety of distros to better understand the inner workings of an operating system.
            As a sidenote, my dotfiles for i3 on ArchLinux can be found <a href="{% url 'projects:view' slug='discomatic' %}">here.</a>
        </p>

        <h2>Hobbies</h2>
        <p>
            I'm also part of the <a href="http://www.facebook.com/UniSouthamptonER">University of Southampton Efficiency
            Racing Team</a>, in which we are
            competing in the Shell Eco-marathon competition with the goal of building an electric car while being as
            efficient as possible. As part of the powertrain team I'll be helping with coding and optimizing the onboard
            computer, but as a true petrolhead I won't be limiting myself to that.
        </p>
    </div>


    {{ block.super }}
{% endblock %}

web/projects/templates/projects/add.html
{% extends 'reflection/base.html' %}
{% load bootstrap3 %}

{% block title %}Add a project // {{ block.super }}{% endblock %}

{% block content %}

  <div class="container">
    <div class="page-header">
      <h1>Add a project</h1>
    </div>

    <form action="" method="post">
      {% csrf_token %}
      {% bootstrap_form form%}
      {% buttons %}
        <button type="submit" class="btn btn-primary">Submit</button>
      {% endbuttons %}
    </form>
  </div>

  {{ block.super }}
{% endblock content %}

web/projects/templates/projects/contact.html
{% extends 'reflection/base.html' %}

{% block title %}Contact // {{ block.super }}{% endblock %}

{% block content %}

    <div class="container">
        <div class="contact accent-links">
            <p><strong>
                <i class="fa fa-envelope" aria-hidden="true">
                </i> Email me at</strong> <a href="{{ links.mail }}">mircea@mihalea.ro</a>
            </p>
            <p><strong><i class="fa fa-facebook" aria-hidden="true"></i> Add me on Facebook</strong>
                <a href="{{ links.facebook }}" target="_blank">facebook.com/mihalea.m</a></p>
            <p><strong><i class="fa fa-linkedin" aria-hidden="true"></i> Send me an InMail at</strong>
                <a href="{{ links.linkedin }}" target="_blank">linkedin.com/in/mircea-mihalea</a></p>
            <p><strong><i class="fa fa-github" aria-hidden="true"></i> Reach me on github</strong>
                <a href="{{ links.github }}" target="_blank">github.com/mihalea</a>
            </p>
        </div>
    </div>


    {{ block.super }}
{% endblock %}

web/projects/templates/projects/index.html
{% extends 'reflection/base.html' %}

{% load staticfiles %}
{% load sass_tags %}

{% block styles %}
  <link href="{% sass_src 'css/cover.scss' %}" rel="stylesheet" type="text/css"/>
{% endblock %}

{% block content %}
  <div class="jumbotron">
    <div class="container cover">
      <div class="row">
        <div class="col-md-4 portrait">
          <img src="{% static 'img/cover.jpg' %}" class="img-circle">
        </div>
        <div class="col-md-8">
          <h1>Hello! I'm Mircea Mihalea!</h1>
          <p>I'm a software developer, petrolhead and linux<!--GNU/Linux--> enthusiast looking to make my life easier through coding.
          I'm currently studying Computer Science at the University of Southampton.</p>
          <p class="social">
            <a href="{{ links.github }}"><i class="fa fa-github-square fa-2x" aria-hidden="true"></i></a>
            <a href="{{ links.facebook }}"><i class="fa fa-facebook-square fa-2x" aria-hidden="true"></i></a>
            <a href="{{ links.linkedin }}"><i class="fa fa-linkedin-square fa-2x" aria-hidden="true"></i></a>
            <a href="{{ links.mail }}"><i class="fa fa-envelope-square fa-2x" aria-hidden="true"></i></a>
          </p>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

web/projects/templates/projects/list.html
{% extends 'reflection/base.html' %}
{% load project_extras %}

{% block title %}Projects // {{ block.super }}{% endblock %}

{% block content %}
  <div class="container">
    <div class="page-header">
      <h1>Featured:</h1>
    </div>

    <div class="row">
      {% for p in featured %}
        <div class="col-lg-4">
          <h3>{{ p.repository }} <small>{{ p.language | lower }}</small></h3>
          <span class="accent-links">{{ p.readme | md | truncatechars_html:500 | striptags }}</span><br/>
          <a href="{{ p.get_absolute_link }}" class="btn btn-danger">View details</a>
        </div>
      {% endfor %}
    </div>

    <div class="page-header">
      <h4>More projects:</h4>
    </div>

    <ul class="accent-links">
    {% for p in not_featured %}
        <li>
        <p><a href="{{ p.get_absolute_link }}">{{ p.repository }}:</a> {{ p.description }}</p>
        </li>
    {% endfor %}
    </ul>
  </div>

  {{ block.super }}

{% endblock content %}

web/projects/templates/projects/view.html
{% extends 'reflection/base.html' %}
{% load project_extras %}

{% block title %}{{ project.repository }} // {{ block.super }}{% endblock %}

{% block content %}
  <div class="container project accent-links">
    <div class="page-header">
        <span class="repo">{{ project.repository }}</span>
        <span class="language">{{ project.language }}</span>

        <a href="http://github.com/{{ project.username }}/{{ project.repository }}" class="github pull-right">GitHub <i class="fa fa-link" aria-hidden="true"></i></a>
    </div>

    <div class="readme">{{ project.readme|md|responsive }}</div>

    <span class="updated pull-right">last commit: {{ project.updated_at|date|lower }}</span>

  </div>

  {{ block.super }}

{% endblock content %}

web/templates/reflection/base.html
{% load staticfiles %}
{% load sass_tags %}
{% load bootstrap3 %}

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">	

    <title>{% block title %}Mihalea{% endblock %}</title>

    <link rel="icon" type="image/x-icon" href="{% static 'favicon.ico' %}"/>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
          integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <!-- Font awesome -->
    <script src="https://use.fontawesome.com/7eb89895cb.js"></script>

    <!-- Google fonts -->
    <link href="https://fonts.googleapis.com/css?family=Raleway:300" rel="stylesheet">


    <link href="{% sass_src 'css/base.scss' %}" rel="stylesheet" type="text/css"/>
    {% block styles %}{% endblock %}

</head>
<body>
{% bootstrap_messages %}

<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url "projects:index" %}"><i class="fa fa-code"
                                                                         aria-hidden="true"> </i>Mircea Mihalea</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                {% url "projects:index" as url %}
                <li {% if url == request.path %}class="active"{% endif %}><a href="{{ url }}">Home</a></li>

                {% url "projects:about" as url %}
                <li {% if url == request.path %}class="active"{% endif %}><a href="{{ url }}">About me</a></li>

                {% url "projects:showcase" as url %}
                <li {% if url == request.path %}class="active"{% endif %}><a href="{{ url }}">Projects</a></li>

                {% url "projects:contact" as url %}
                <li {% if url == request.path %}class="active"{% endif %}><a href="{{ url }}">Contact</a></li>
            </ul>
        </div><!--/.navbar-collapse  -->
    </div>
</nav>
{% block content %}
    <footer class="footer">
        <div class="container">
            <p class="text-muted"><i class="fa fa-copyright" aria-hidden="true"></i> Mircea Mihalea 2016-2017</p>
        </div>
    </footer>
{% endblock content %}
<script src='https://code.jquery.com/jquery-2.1.4.min.js'></script>
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous"></script>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-86287590-1', 'auto');
  ga('send', 'pageview');

</script>
</body>
</html>